% Ensayo con el Lorenz 96 para el análisis de distribuciones

clear all
close all
clc

Tsim=200;
dt=0.01; %step length
m=40;
n=100;
F=8;
sigma=40e-1;
R=sigma^2*eye(m);
H = eye(n,n); 
H = H(randperm(n,m),:);


N=60;               % Number of ensembles
sparse=1 % Sparse of the initial ensemble
% imagesc(H)    %plot measurenment states to know which states are being observed
% xlabel('State number');
% ylabel('Observation');


%===Generate real state===
x0=1*randn(n,1);
[Xreal]=Lorenz_96(Tsim,dt,x0,F);


%==================================================================
% Enemble forward propagation


x00=-sparse/2+sparse*rand(n,N); %The ensemble is generated by the initial condition
xb(:,1,:)=x00;


for i=2:Tsim
    for Nen=1:N %Propagation in time of all the ensemble members to generate background
        [xb(:,i,Nen),t]=Lorenz_96_one_step(1,dt,squeeze(xb(:,i-1,Nen)),F);  
    end
    
end

plot(squeeze(xb(1,:,:)))



